<!DOCTYPE html>
<html>
<head>
    <title>Profit & Loss Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #333; }
        .header p { margin: 5px 0; color: #666; }
        .info-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .info-table td { padding: 8px; border: 1px solid #ddd; }
        .info-table .label { font-weight: bold; width: 30%; background-color: #f5f5f5; }
        .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .summary-table th, .summary-table td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        .summary-table th { background-color: #f2f2f2; font-weight: bold; }
        .highlight { font-weight: bold; }
        .profit { color: #28a745; }
        .loss { color: #dc3545; }
        .missing-items { margin-top: 30px; }
        .missing-items h3 { color: #dc3545; margin-bottom: 10px; }
        .footer { margin-top: 30px; text-align: right; font-size: 12px; color: #777; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Profit & Loss Report</h1>
        <p>Generated on: {{ date('F j, Y, g:i a') }}</p>
    </div>

    <table class="info-table">
        <tr>
            <td class="label">Report Period:</td>
            <td>{{ date('F j, Y', strtotime($fromDate)) }} to {{ date('F j, Y', strtotime($toDate)) }}</td>
        </tr>
        <tr>
            <td class="label">Days Covered:</td>
            <td>{{ \Carbon\Carbon::parse($fromDate)->diffInDays(\Carbon\Carbon::parse($toDate)) + 1 }} days</td>
        </tr>
    </table>

    <table class="summary-table">
        <thead>
            <tr>
                <th>Metric</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Total Revenue</td>
                <td>${{ number_format($totalRevenue, 2) }}</td>
            </tr>
            <tr>
                <td>Total Cost of Goods Sold (COGS)</td>
                <td>${{ number_format($totalCOGS, 2) }}</td>
            </tr>
            <tr class="highlight">
                <td>Profit/Loss</td>
                <td class="{{ $profitOrLoss >= 0 ? 'profit' : 'loss' }}">
                    ${{ number_format(abs($profitOrLoss), 2) }} ({{ $profitOrLoss >= 0 ? 'Profit' : 'Loss' }})
                </td>
            </tr>
            <tr>
                <td>Gross Margin</td>
                <td>
                    @if($totalRevenue > 0)
                        {{ number_format(($profitOrLoss / $totalRevenue) * 100, 2) }}%
                    @else
                        N/A
                    @endif
                </td>
            </tr>
        </tbody>
    </table>

    @if(count($missingCostProducts) > 0)
    <div class="missing-items">
        <h3>⚠️ Products With Missing Cost Data</h3>
        <p>The following products were sold but had no purchase records, so their COGS was calculated as $0:</p>

        <table class="summary-table">
            <thead>
                <tr>
                    <th>Product ID</th>
                    <th>Product Name</th>
                    <th>Quantity Sold</th>
                </tr>
            </thead>
            <tbody>
                @foreach($missingCostProducts as $product)
                <tr>
                    <td>{{ $product['product_id'] }}</td>
                    <td>{{ $product['product_name'] }}</td>
                    <td>{{ $product['quantity'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <p class="highlight">Note: Including these products' actual costs would increase COGS by at least ${{ number_format($totalRevenue - $profitOrLoss, 2) }}.</p>
    </div>
    @endif

    <div class="footer">
        <p>Report generated by {{ config('app.name') }}</p>
    </div>
</body>
</html>
